### ISSUE TITLE
Pip install error

### ISSUE THREAD

**Issue by Galatolol** [clearclaw/xxpaper#8]
```$ pip3 install xxpaper
Collecting xxpaper
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/88/d2/f5f28889b6a9228a76ea90892a391e92aa8b43544d7f5e2acc69f95a9193/xxpaper-1.0.post71.tar.gz (827kB)
    100% |████████████████████████████████| 829kB 1.5MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-f0mrjng3/xxpaper/setup.py", line 22, in <module>
        for line in file ("requirements.txt").readlines ()],
    NameError: name 'file' is not defined
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-f0mrjng3/xxpaper/
```

I think that you forgot to update the source which is used by pip.
(it's `open ("requirements.txt")` here on github)

**Comment by clearclaw** [comment]
I'm going to guess that you were trying to use Python 3 -- before XXPaper supported Python 3.  The current release does support Python 3 and should fix that problem.
